services:
  - type: web
    name: novamind-backend
    env: docker
    rootDir: backend/back
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: NovaMind
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MYSQL_ATTR_SSL_CA
        sync: false
      - key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
